//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICER.MIGRACION.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SICER_INT_SBOEntities : DbContext
    {
        public SICER_INT_SBOEntities()
            : base("name=SICER_INT_SBOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<MSS_SP_SICER_ACCOUNTINFO_Result> MSS_SP_SICER_ACCOUNTINFO(string curr, Nullable<System.DateTime> date, string cC5)
        {
            var currParameter = curr != null ?
                new ObjectParameter("Curr", curr) :
                new ObjectParameter("Curr", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var cC5Parameter = cC5 != null ?
                new ObjectParameter("CC5", cC5) :
                new ObjectParameter("CC5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_ACCOUNTINFO_Result>("MSS_SP_SICER_ACCOUNTINFO", currParameter, dateParameter, cC5Parameter);
        }
    
        public virtual ObjectResult<MSS_SP_SICER_ACCOUNTPAYMENTS_Result> MSS_SP_SICER_ACCOUNTPAYMENTS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_ACCOUNTPAYMENTS_Result>("MSS_SP_SICER_ACCOUNTPAYMENTS");
        }
    
        public virtual ObjectResult<MSS_SP_SICER_BUSINESSPARTNERS_Result> MSS_SP_SICER_BUSINESSPARTNERS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_BUSINESSPARTNERS_Result>("MSS_SP_SICER_BUSINESSPARTNERS");
        }
    
        public virtual ObjectResult<MSS_SP_SICER_CUENTASPAGO_Result> MSS_SP_SICER_CUENTASPAGO(Nullable<int> docType, Nullable<int> exCode)
        {
            var docTypeParameter = docType.HasValue ?
                new ObjectParameter("DocType", docType) :
                new ObjectParameter("DocType", typeof(int));
    
            var exCodeParameter = exCode.HasValue ?
                new ObjectParameter("ExCode", exCode) :
                new ObjectParameter("ExCode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_CUENTASPAGO_Result>("MSS_SP_SICER_CUENTASPAGO", docTypeParameter, exCodeParameter);
        }
    
        public virtual int MSS_SP_SICER_CUENTASVALIDAS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MSS_SP_SICER_CUENTASVALIDAS");
        }
    
        public virtual ObjectResult<MSS_SP_SICER_DATOSERETAPA1_Result> MSS_SP_SICER_DATOSERETAPA1(Nullable<int> exCode)
        {
            var exCodeParameter = exCode.HasValue ?
                new ObjectParameter("ExCode", exCode) :
                new ObjectParameter("ExCode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_DATOSERETAPA1_Result>("MSS_SP_SICER_DATOSERETAPA1", exCodeParameter);
        }
    
        public virtual ObjectResult<MSS_SP_SICER_FACTURACIONWEB_Result> MSS_SP_SICER_FACTURACIONWEB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_FACTURACIONWEB_Result>("MSS_SP_SICER_FACTURACIONWEB");
        }
    
        public virtual ObjectResult<MSS_SP_SICER_FACTURACIONWEBDETALLE_Result> MSS_SP_SICER_FACTURACIONWEBDETALLE(Nullable<int> exCode, Nullable<int> docType, Nullable<int> etapa, Nullable<int> idFactura)
        {
            var exCodeParameter = exCode.HasValue ?
                new ObjectParameter("ExCode", exCode) :
                new ObjectParameter("ExCode", typeof(int));
    
            var docTypeParameter = docType.HasValue ?
                new ObjectParameter("DocType", docType) :
                new ObjectParameter("DocType", typeof(int));
    
            var etapaParameter = etapa.HasValue ?
                new ObjectParameter("Etapa", etapa) :
                new ObjectParameter("Etapa", typeof(int));
    
            var idFacturaParameter = idFactura.HasValue ?
                new ObjectParameter("IdFactura", idFactura) :
                new ObjectParameter("IdFactura", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_FACTURACIONWEBDETALLE_Result>("MSS_SP_SICER_FACTURACIONWEBDETALLE", exCodeParameter, docTypeParameter, etapaParameter, idFacturaParameter);
        }
    
        public virtual ObjectResult<MSS_SP_SICER_FACTURASRENDIDASER_Result> MSS_SP_SICER_FACTURASRENDIDASER(Nullable<int> exCode, string curr)
        {
            var exCodeParameter = exCode.HasValue ?
                new ObjectParameter("ExCode", exCode) :
                new ObjectParameter("ExCode", typeof(int));
    
            var currParameter = curr != null ?
                new ObjectParameter("Curr", curr) :
                new ObjectParameter("Curr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_FACTURASRENDIDASER_Result>("MSS_SP_SICER_FACTURASRENDIDASER", exCodeParameter, currParameter);
        }
    
        public virtual int MSS_SP_SICER_GRUPOSFACTURACION()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MSS_SP_SICER_GRUPOSFACTURACION");
        }
    
        public virtual ObjectResult<MSS_SP_SICER_JOURNALENTRIESHEADER_Result> MSS_SP_SICER_JOURNALENTRIESHEADER()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_JOURNALENTRIESHEADER_Result>("MSS_SP_SICER_JOURNALENTRIESHEADER");
        }
    
        public virtual ObjectResult<MSS_SP_SICER_JOURNALENTRIESLINES_Result> MSS_SP_SICER_JOURNALENTRIESLINES(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_JOURNALENTRIESLINES_Result>("MSS_SP_SICER_JOURNALENTRIESLINES", idParameter);
        }
    
        public virtual ObjectResult<MSS_SP_SICER_PAYROLLINVOICES_Result> MSS_SP_SICER_PAYROLLINVOICES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_PAYROLLINVOICES_Result>("MSS_SP_SICER_PAYROLLINVOICES");
        }
    
        public virtual ObjectResult<MSS_SP_SICER_PENDINGINVOICES_Result> MSS_SP_SICER_PENDINGINVOICES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_PENDINGINVOICES_Result>("MSS_SP_SICER_PENDINGINVOICES");
        }
    
        public virtual ObjectResult<Nullable<int>> MSS_SP_SICER_PRIMERAETAPA(Nullable<int> exCode)
        {
            var exCodeParameter = exCode.HasValue ?
                new ObjectParameter("ExCode", exCode) :
                new ObjectParameter("ExCode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MSS_SP_SICER_PRIMERAETAPA", exCodeParameter);
        }
    
        public virtual ObjectResult<MSS_SP_SICER_PURCHASEINVOICES_Result> MSS_SP_SICER_PURCHASEINVOICES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_PURCHASEINVOICES_Result>("MSS_SP_SICER_PURCHASEINVOICES");
        }
    
        public virtual ObjectResult<MSS_SP_SICER_PURCHASEINVOICESLINES_Result> MSS_SP_SICER_PURCHASEINVOICESLINES(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_PURCHASEINVOICESLINES_Result>("MSS_SP_SICER_PURCHASEINVOICESLINES", idParameter);
        }
    
        public virtual ObjectResult<MSS_SP_SICER_REFACTURABLES_Result> MSS_SP_SICER_REFACTURABLES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_REFACTURABLES_Result>("MSS_SP_SICER_REFACTURABLES");
        }
    
        public virtual ObjectResult<MSS_SP_SICER_RENDICIONESSEGUNDAETAPA_Result> MSS_SP_SICER_RENDICIONESSEGUNDAETAPA(Nullable<int> exCode, string curr)
        {
            var exCodeParameter = exCode.HasValue ?
                new ObjectParameter("ExCode", exCode) :
                new ObjectParameter("ExCode", typeof(int));
    
            var currParameter = curr != null ?
                new ObjectParameter("Curr", curr) :
                new ObjectParameter("Curr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_RENDICIONESSEGUNDAETAPA_Result>("MSS_SP_SICER_RENDICIONESSEGUNDAETAPA", exCodeParameter, currParameter);
        }
    
        public virtual int MSS_SP_SICER_TRASLADOFACTURAS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MSS_SP_SICER_TRASLADOFACTURAS");
        }
    
        public virtual ObjectResult<MSS_SP_SICER_WEBUDOINVOICES_Result> MSS_SP_SICER_WEBUDOINVOICES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_WEBUDOINVOICES_Result>("MSS_SP_SICER_WEBUDOINVOICES");
        }
    }
}
